name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.4
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2
  equatable: ^2.0.5
  path_provider: ^2.1.1  # Add this for Hive initialization
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  # Only include assets that exist
  assets:
    - assets/images/  # Make sure this directory exists
    # - assets/icon/  # Remove if directory doesn't exist