name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.4
  flutter_easyloading: ^3.0.5
  animate_do: ^4.2.0
  google_fonts: ^6.2.1
  awesome_dialog: ^3.2.1
  rive: ^0.13.20
  jwt_decoder: ^2.0.1
  accordion: ^2.6.0
  intl: ^0.20.2
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Only include assets that exist
  assets:
    - assets/images/  # Make sure this directory exists
    # - assets/icon/  # Remove if directory doesn't exist